# Make search index for javascript and copy pdfs to ../unlabelled folder

# 個人情報などを、別の場所にまとめることにした。
# PRIVATE=~/Unison/00Priority/2022錯討

special.json: special.xlsx special.py
	python special.py $< > $@
